update default value for cpu/memory
kinueng/code-engine-toolchain pull request #8
Opened 2022-09-06 18:40 UTC by aknguyen7

2022-09-06 20:29 UTC, kinueng requested changes

2022-09-06 20:29 UTC, kinueng commented on .tekton/tasks/task-deploy-to-code-engine.yml
> +      default: "0.125"
```suggestion
      default: "0.25"
```

2022-09-06 20:53 UTC, aknguyen7 commented on .tekton/tasks/task-deploy-to-code-engine.yml
> +      default: "0.125"
line 29 is correct, I updated line 38 from 0.5 to 0.25

2022-09-29 14:16 UTC, kinueng approved these changes

2022-09-29 14:17 UTC, merged